# Generated by Django 5.0.6 on 2024-07-23 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0020_rename_country_destination_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 7, 23, 14, 38, 14, 699499, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
