# Generated by Django 5.0.6 on 2024-07-24 03:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0021_alter_transactions_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessanger_detail',
            name='pay_done',
        ),
        migrations.AddField(
            model_name='pessanger_detail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessanger_detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='Trip_same_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pessanger_detail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 7, 24, 3, 9, 35, 174053, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
