# Generated by Django 5.0.6 on 2024-07-15 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0017_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 7, 15, 9, 25, 42, 290492, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
