# Generated by Django 5.0.6 on 2024-07-23 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0019_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='country',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='detailed_desc',
            old_name='country',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 7, 23, 7, 9, 38, 876949, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
